-- Real founding work requested by the owner. No fabricated people or outcomes.
-- Stable IDs match lib/harness.ts; never overwrite task progress during provisioning.
begin;
insert into public.tasks (id,project_id,title,discipline,level,effort,technology,objective,context,acceptance,dependencies,reviewer,assignee,issue_url,status,is_demo) values
('cf100000-0000-4000-8000-000000000001','cf000000-0000-4000-8000-000000000001','Establish the independent harness team','Security','Specialist','Ongoing','Security review · GitHub','Give the community an accountable review team before widening release access.','The platform is being handed to human maintainers. Contributor, reviewer and release authority must remain separate. No security team has been appointed yet.','Publish consenting maintainer and security reviewer contacts; document conflicts of interest and coverage; configure protected main with required checks and fresh independent reviews; prove a failing pull request cannot merge; record provider evidence.','Owner appoints trusted reviewers and approves repository settings.','Repository owner; independent security reviewer to be appointed','Unassigned',null,'OPEN',false),
('cf100000-0000-4000-8000-000000000002','cf000000-0000-4000-8000-000000000001','Verify accounts and data isolation with real users','Backend','Advanced','Multi-day','Supabase · PostgreSQL · Next.js','Enable shared community work only after isolation is verified on the hosted system.','Migrations and protected actions are implemented locally. Production account infrastructure needs an explicitly approved dedicated database and provider configuration.','Configure approved database and authentication; test anonymous, two-member and maintainer sessions; demonstrate blocked cross-user edits and role escalation; test revoked sessions, callback origins and rate limits; attach sanitized test evidence.','Dedicated Supabase project approval; harness reviewer assigned.','Backend maintainer and independent security reviewer','Unassigned',null,'OPEN',false),
('cf100000-0000-4000-8000-000000000003','cf000000-0000-4000-8000-000000000001','Test the complete contribution journey for accessibility','Accessibility','Intermediate','3–8 hours','Keyboard · Screen reader · WCAG','Make joining, finding work, discussing and submitting usable without a mouse.','Automated checks cannot establish usability. Test the actual shared workflow in both color themes and on mobile.','Complete the journey using keyboard and a screen reader; record focus order, announcements and errors; verify light/dark contrast and 200% zoom; file reproducible issues and retest fixes.','Stable preview; authenticated journey available for full coverage.','Accessibility reviewer independent of the fixes','Unassigned',null,'OPEN',false),
('cf100000-0000-4000-8000-000000000004','cf000000-0000-4000-8000-000000000001','Write the first human maintainer handoff','Documentation','First Contribution','1–3 hours','Markdown · GitHub','Let a new maintainer understand and continue the work without this chat.','Use the repository, harness charter and current deployment evidence. Separate implemented code from configured services and future work.','A new contributor can identify the current goal, open blockers, local setup, tests, review rules and release owner; every operational claim links to evidence; no credentials or invented people appear.','Access to the current public source and release record.','Project maintainer','Unassigned',null,'OPEN',false),
('cf100000-0000-4000-8000-000000000005','cf000000-0000-4000-8000-000000000001','Design a respectful first contribution experience','UX/UI','Intermediate','3–8 hours','Interaction design · User research','Help people choose useful work by skill, time and interest without turning contribution into a popularity contest.','Human contributors need autonomy, clear expectations, help and a way to hand off work when their availability changes.','Test the flow with at least three consenting contributors; publish anonymized findings; show claim, ask-for-help and handoff states; include non-code roles and low-bandwidth/mobile use.','Recruit consenting testers; no public personal research data.','Design maintainer and accessibility reviewer','Unassigned',null,'OPEN',false),
('cf100000-0000-4000-8000-000000000006','cf000000-0000-4000-8000-000000000001','Exercise the review boundary against hostile contributions','Testing','Advanced','3–8 hours','Threat modeling · Integration tests','Demonstrate that untrusted contributions cannot gain authority or ship themselves.','Use a staging environment with synthetic data. Test malicious links, abusive content, task races, self-approval and dependency changes without running untrusted code with production secrets.','Publish a threat model and reproducible safe tests; prove self-approval and unauthorized completion are rejected; demonstrate stale evidence blocks acceptance; verify that application task completion cannot trigger a production deploy.','Hosted staging auth; independent review and release controls configured.','Harness security reviewer','Unassigned',null,'OPEN',false),
('cf100000-0000-4000-8000-000000000007','cf000000-0000-4000-8000-000000000001','Rehearse a release and rollback with a human steward','DevOps','Advanced','3–8 hours','Vercel · GitHub Actions','Make every release attributable, reviewable and recoverable.','A successful build is evidence, not authorization. Keep public contributor CI separate from hosting credentials and production approval.','Record source SHA, preview URL, check results and independent approvals; prove unauthorized deployment denied; rehearse rollback in staging; verify the released URL and record an owner-approved production procedure.','Harness team appointed; hosting release permissions reviewed.','Repository owner and security reviewer','Unassigned',null,'OPEN',false)
on conflict (id) do nothing;
commit;
